#pragma once

namespace perception {
namespace radar {

const double PI = 3.1415926535898;
const int MAX_RADAR_IDX = 2147483647;
// const double CONTI_ARS_INTERVAL = 0.074;
const int ORIGIN_CHENGTECH_MAX_ID_NUM = 255;
const double MIN_PROBEXIST = 0.08;

enum ChengtechObjectType {
  CHENGTECH_POINT = 0,
  CHENGTECH_CAR = 1,
  CHENGTECH_TRUCK = 2,
  CHENGTECH_PEDESTRIAN = 3,
  CHENGTECH_MOTOCYCLE = 4,
  CHENGTECH_BICYCLE = 5,
  CHENGTECH_WIDE = 6,
  CHENGTECH_TYPE_UNKNOWN = 7,
  CHENGTECH_MAX_OBJECT_TYPE = 8
};

enum ChengtechSpdMode {
  CHENGTECH_OBD = 1,  //
  CHENGTECH_SVM = 2,  // 自测速
};

enum ChengtechDynProp {
  CHENGTECH_DYNAMIC_UNKNOWN = 0,  // 不详
  CHENGTECH_ONCOMING = 1,         // 来向
  CHENGTECH_MOVING = 2,           // 去向
  CHENGTECH_STATIONARY = 3,       // 静止
  // CONTI_STATIONARY_CANDIDATE = 3,
  // CONTI_CROSSING_STATIONARY = 5,
  // CONTI_CROSSING_MOVING = 6,
  // CONTI_STOPPED = 7
};

enum ChengtechErrorCode {
  CHENGTECH_INIT_FAILED = 100,
  CHENGTECH_WRONG_YAW_RATE = 101,
  CHENGTECH_WRONG_SPEED_INPUT = 102,
  CHENGTECH_MMIC_TEMPERTURE = 110,
  CHENGTECH_MCU_TEMPERTURE = 111,
  CHENGTECH_FALSH_HEAD_ERROR = 112,
  CHENGTECH_FALSH_CRC_ERROR = 113,
  CHENGTECH_CALIB_FAILED = 113,
  CHENGTECH_CALIB_ANGLE_ERROR = 114,
  CHENGTECH_INSTALL_ANGLE_ERROR = 130,
};

}  // namespace radar
}  // namespace perception
