include: common.yaml
map:
  include: map/dali/dali_config.yaml

ground_filter:
  ground_height_ranges: [0.35, 0.35, 0.6, 0.8]

refiner:
  enable_PedFilter: false
  floating_height_limited: 1.3 # TODO:  This value can be computed dynamically by ground values
