// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hm_matcher_conf.proto

#ifndef PROTOBUF_hm_5fmatcher_5fconf_2eproto__INCLUDED
#define PROTOBUF_hm_5fmatcher_5fconf_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace perception {
namespace mid_fusion {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_hm_5fmatcher_5fconf_2eproto();
void protobuf_AssignDesc_hm_5fmatcher_5fconf_2eproto();
void protobuf_ShutdownFile_hm_5fmatcher_5fconf_2eproto();

class HmMatcherConf;

// ===================================================================

class HmMatcherConf : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:perception.mid_fusion.HmMatcherConf) */ {
 public:
  HmMatcherConf();
  virtual ~HmMatcherConf();

  HmMatcherConf(const HmMatcherConf& from);

  inline HmMatcherConf& operator=(const HmMatcherConf& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HmMatcherConf& default_instance();

  void Swap(HmMatcherConf* other);

  // implements Message ----------------------------------------------

  inline HmMatcherConf* New() const { return New(NULL); }

  HmMatcherConf* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HmMatcherConf& from);
  void MergeFrom(const HmMatcherConf& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(HmMatcherConf* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double max_match_distance = 1;
  bool has_max_match_distance() const;
  void clear_max_match_distance();
  static const int kMaxMatchDistanceFieldNumber = 1;
  double max_match_distance() const;
  void set_max_match_distance(double value);

  // optional double bound_match_distance = 2;
  bool has_bound_match_distance() const;
  void clear_bound_match_distance();
  static const int kBoundMatchDistanceFieldNumber = 2;
  double bound_match_distance() const;
  void set_bound_match_distance(double value);

  // @@protoc_insertion_point(class_scope:perception.mid_fusion.HmMatcherConf)
 private:
  inline void set_has_max_match_distance();
  inline void clear_has_max_match_distance();
  inline void set_has_bound_match_distance();
  inline void clear_has_bound_match_distance();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double max_match_distance_;
  double bound_match_distance_;
  friend void  protobuf_AddDesc_hm_5fmatcher_5fconf_2eproto();
  friend void protobuf_AssignDesc_hm_5fmatcher_5fconf_2eproto();
  friend void protobuf_ShutdownFile_hm_5fmatcher_5fconf_2eproto();

  void InitAsDefaultInstance();
  static HmMatcherConf* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// HmMatcherConf

// optional double max_match_distance = 1;
inline bool HmMatcherConf::has_max_match_distance() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HmMatcherConf::set_has_max_match_distance() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HmMatcherConf::clear_has_max_match_distance() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HmMatcherConf::clear_max_match_distance() {
  max_match_distance_ = 0;
  clear_has_max_match_distance();
}
inline double HmMatcherConf::max_match_distance() const {
  // @@protoc_insertion_point(field_get:perception.mid_fusion.HmMatcherConf.max_match_distance)
  return max_match_distance_;
}
inline void HmMatcherConf::set_max_match_distance(double value) {
  set_has_max_match_distance();
  max_match_distance_ = value;
  // @@protoc_insertion_point(field_set:perception.mid_fusion.HmMatcherConf.max_match_distance)
}

// optional double bound_match_distance = 2;
inline bool HmMatcherConf::has_bound_match_distance() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HmMatcherConf::set_has_bound_match_distance() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HmMatcherConf::clear_has_bound_match_distance() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HmMatcherConf::clear_bound_match_distance() {
  bound_match_distance_ = 0;
  clear_has_bound_match_distance();
}
inline double HmMatcherConf::bound_match_distance() const {
  // @@protoc_insertion_point(field_get:perception.mid_fusion.HmMatcherConf.bound_match_distance)
  return bound_match_distance_;
}
inline void HmMatcherConf::set_bound_match_distance(double value) {
  set_has_bound_match_distance();
  bound_match_distance_ = value;
  // @@protoc_insertion_point(field_set:perception.mid_fusion.HmMatcherConf.bound_match_distance)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace mid_fusion
}  // namespace perception

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_hm_5fmatcher_5fconf_2eproto__INCLUDED
