#@brief: config file for perception
roadmap:
  map_list:
    - city: hengyang
      utm_zone: 49
      mappath: hengyang/V3.4.1
      version: V3.4.1

    - city: fuzhou
      utm_zone: 50
      mappath: fuzhou/V1.2
      version: V1.2

    - city: tianjin
      utm_zone: 50
      mappath: tianjin/V1.3
      version: V1.3
      
    - city: beijing
      utm_zone: 50
      mappath: beijing/V3.4.1
      version: V3.4.1

    - city: dali
      utm_zone: 47
      mappath: dali/V1.7
      version: V1.7

    - city: yantai
      utm_zone: 51
      mappath: yantai/V1.8.1
      version: V1.8.1

is_lock_localization: false
is_print_timecost: false
is_showTime_local_lidar: false
is_inter_localization: false
rain_mode_init_open: false #雨天模式，通过yaml/Pad开关
is_send_pointcloud: false
is_process_semanticmap: true
common:
  data_fusion: false
  cone_filter:
    hack_area_x: 658399.797653
    hack_area_y: 2967928.156141
    hack_area_distance: 500
  uphill_filter:
    hack_area_x: 380117.854300
    hack_area_y: 4148853.776201
    hack_area_distance: 100

preprocessing:
  # 车体坐标系下过滤车体范围内点云
  vehicle_filter:
    enable: false
    xmin: -2.
    xmax: 5.2
    ymin: -2.
    ymax: 2.
    zmin: -2.
    zmax: 2.
  range_filter:
    enable: false
  noise_point:
    polyfit_a: -0.4
    polyfit_c: 90
    grid_size: 1
    todel_ingrid_percept: 0.1
    noise_ingrid_percent: 0.25

roi_filter:
  enable: true
  unit_size: 0.2
  show_element_value: 1
  roadside_valid_flag: true
  curload_allowance_dist: 20

denoise:
  enable: false
  model: denoise_grid_0523.json
  confidence: 0.49347338
  obj_model: denoise_obj_0523.json
  obj_confidence: 0.60116196
  detect_range:
    xmin: -20
    xmax: 50
    ymin: -20
    ymax: 20
    zmin: 0.2
    zmax: 2.5
  unit_size: 1.

ai_detection:
  enable: false
  use_confidencemap: true
  use_fp_16: true
  use_cuda: true
  lidar_type: ""
  device_id: 0
  max_workspace: 30

ai_refine:
  enable: false
  use_fp_16: true
  use_cuda: true
  lidar_type: ""
  device_id: 0
  max_workspace: 30
  batch_size: 8


ground_filter:
  enable: false
  setDistanceThreshold: 0.2
  use_falcon_distance : 30
  cell_distance_ranges: [0, 15, 30, 45]
  ground_height_ranges: [0.8, 0.8, 0.8, 0.8]
  inner_cell_diff_ranges: [0.2, 0.25, 0.35, 0.35]
  adjacent_cell_diff_ranges: [0.2, 0.25, 0.35, 0.35]
  cell_zmin_ranges: [0.1,0.1,0.1,0.1]
  cell_zmax_ranges: [2.0,2.0,2.0,2.0]  
  
segmentor:
  enable: false
  split: true #rb大目标切割开关
  split_floating_obj: false #rb浮空目标切割开关
  seg_min_pts: 3
  xgrid_thre: 5 #unit is grid num
  ygrid_thre: 5 #unit is grid num
  init_thre: 1.5 #unit is meter
  split_thre_road: 60 #unit is grid
  split_thre_roadside: 25 #unit is grid
  split_floating_zthre: 1.4 #unit is meter

refiner:
  enable: true
  floating_filter: false
  floating_range:
    xmin: -30
    xmax: 35
    ymin: -30
    ymax: 30
    zmin: 0.2 
    zmax: 2.5
  floating_object_size: [1.0, 1.0, 0.4]
  floating_height_limited: 1.4 # TODO:  This value can be computed dynamically by ground values
  ghost_filter: false
  ghost_range:
    xmin: 5.4
    xmax: 15
    ymin: -5
    ymax: 5
    zmin: 0.31
    zmax: 1.3
  ghost_size: [0.51, 1.0, 1.0]  # length, width, height
  flowerbed_filter: false
  flowerbed_range:
    xmin: -30
    xmax: 30
    ymin: -30
    ymax: 30
    zmin: -0.5 
    zmax: 2.5
  flowerbed_object_size: [1.0, 1.0, 0.2]
  flowerbed_height_limited: 1.0 # TODO:  This value can be computed dynamically by ground values
  pps_isfalcon: false
  airefine_batch_size: 2
  expand_proposal_meter: 0.8
  proposal_cls_thres: 1.0
  other_expand_ratio: 0.5
  enable_AIRoiFilter: false
  enable_VegetTag: true
  enable_PedFilter: true
  enable_BoxRefine: true

tracker: 
  enable: true
  respective_match: false
  thredist: 2.5
  thredistmax: 4.0
  thredistmin: 0.35
  threheading: 0.349
  det2actthre: 2
  det2freethre: 0
  active2freethre: 5
  maintainAItimes: 8

rule_segment:
  enable: true
  downsampling_ratio: 0.5

debug_log_info:
  perception: false # perception函数debug log功能开关
  tracking: false # tracking函数debug log功能开关
  collect: false # collect函数debug开关
  xmax: 35.
  xmin: 5.
  ymax: 2.
  ymin: -2.

rviz:
  enable: true #rviz 功能开关
  debug_mode: true #debug显示开关
  frame_id: base_link  # rviz显示topic使用的frame id
